# Generated by Django 5.1.1 on 2025-02-05 21:39

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
    migrations.AddField(
        model_name='customuser',
        name='travel_preferences',
        field=models.CharField(max_length=255, blank=True, null=True),
    ),
]
