# Generated by Django 5.1.1 on 2024-10-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='travel_preferences',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
