# Generated by Django 5.1.2 on 2024-10-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_account_locked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='account_locked',
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
