# Generated by Django 5.1.3 on 2024-11-12 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_account_locked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='travel_preferences',
        ),
        migrations.CreateModel(
            name='TravelPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_type', models.CharField(blank=True, max_length=100, null=True)),
                ('transportation', models.CharField(blank=True, max_length=100, null=True)),
                ('airline', models.CharField(blank=True, max_length=100, null=True)),
                ('seating_class', models.CharField(blank=True, max_length=100, null=True)),
                ('meal', models.CharField(blank=True, max_length=100, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
