# Generated by Django 5.1.1 on 2025-04-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="carrier_code",
            field=models.CharField(default="AAAA", max_length=5),
        ),
        migrations.AddField(
            model_name="booking",
            name="flight_number",
            field=models.CharField(default="AAAA", max_length=5),
            preserve_default=False,
        ),
    ]
